name: lollipop
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - pandas
  - zstandard
  - bcbio-gff
  - ruamel.yaml
  - strictyaml
  - tqdm
  - click
  - click-option-group
  - poetry-core >= 1.0.8
  - poetry-dynamic-versioning
  - dask[complete]
