variants_list:
  - B.1.1.7
  - B.1.351
  - P.1
  - B.1.617.2
  - B.1.617.1

variants_pangolin:
  al: B.1.1.7
  be: B.1.351
  ga: P.1
  de: B.1.617.2
  ka: B.1.617.1
  B16173: B.1.617.3

variants_not_reported:
 - BA.2.12.1
 - phe-BA.1
 - phe-BA.2
 - C.36.3
 - B.1.617.3
 - AY.4.2
 - mu
 - d614g
 - BA.1
 - BA.2
 - BA.4
 - BA.5
 - om275

start_date: '2021-01-01'
end_date: '2021-09-01'

to_drop:
 - subset
 - revert
# - shared

cities_list:
 - "Lugano (TI)"
 - "Zürich (ZH)"
 - "Chur (GR)"
 - "Altenrhein (SG)"
 - "Laupen (BE)"
# - "Genève (GE)"
# - "Basel (catchment area ARA Basel)"
 - "Lausanne (VD)"
# - "Kanton Zürich"
