[tool.poetry]
name = "lollipop"
version = "0.1.0"
description = "tool for Deconvolution for Wastewater Genomics"
authors = ["David Dreifuss <dadreifuss@gmail.com>", "Ivan Blagoev Topolsky <ivan.topolsky@bsse.ethz.ch>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/cbg-ethz/LolliPop"

[tool.poetry.dependencies]
python = "^3.10"
numpy = ">=1.23"
scipy = ">=1.9"
pandas = ">=1.5"
"ruamel.yaml" = ">=0.15.80"
tqdm = ">=4.64"
#click = "^8.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
#pytest = "^6.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
