name: ipylollipop
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ipykernel
  - ipywidgets
  - matplotlib
  - seaborn
  - scikit-learn
  - lollipop


# don't forget to run:
# ```
# conda activate ipylollipop
# python -m ipykernel install --user --name=lollipop
# ```

