name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            lfs: false
            # NOTE to save on bandwidth costs, GitHub Action will not use GitHub's own LFS

      - name: Fetch test-data
        # NOTE to save on bandwidth costs, pull data from BSSE's GitLab LFS instead
        run: |
          git config --file .lfsconfig lfs.url "https://git.bsse.ethz.ch/cbg/viruses/lollipop.git/info/lfs"
          git lfs install
          git lfs pull
          git lfs checkout

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Poetry Dynamic Versioning
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Build package
        run: |
          poetry install --extras "cli"
          poetry build

      - name: Test package
        run: |
          poetry run pytest -v

      - name: Lint package
        run: poetry run black --check --diff .

      - name: Archive test output
        uses: actions/upload-artifact@v4
        with:
          name: test_curves
          path: |
            test_results.*
          if-no-files-found: error
